/*
 * Application Manager API
 *
 * Application Manager APIs to control Apache Flink jobs
 *
 * API version: 2.6.1
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Handler defines a specific action that should be taken
//+kubebuilder:object:generate=true
type V1Handler struct {
	Exec      *V1ExecAction      `json:"exec,omitempty"`
	HttpGet   *V1HttpGetAction   `json:"httpGet,omitempty"`
	TcpSocket *V1TcpSocketAction `json:"tcpSocket,omitempty"`
}
