/*
 * Application Manager API
 *
 * Application Manager APIs to control Apache Flink jobs
 *
 * API version: 2.6.1
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
type DeploymentMetadata struct {
	Annotations     map[string]string `json:"annotations,omitempty"`
	CreatedAt       metav1.Time       `json:"createdAt,omitempty"`
	DisplayName     string            `json:"displayName,omitempty"`
	Id              string            `json:"id,omitempty"`
	Labels          map[string]string `json:"labels,omitempty"`
	ModifiedAt      metav1.Time       `json:"modifiedAt,omitempty"`
	Name            string            `json:"name,omitempty"`
	Namespace       string            `json:"namespace,omitempty"`
	ResourceVersion int32             `json:"resourceVersion,omitempty"`
}
