/*
 * Application Manager API
 *
 * Application Manager APIs to control Apache Flink jobs
 *
 * API version: 2.6.1
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// ObjectFieldSelector selects an APIVersioned field of an object.
type V1ObjectFieldSelector struct {
	// Version of the schema the FieldPath is written in terms of, defaults to \"v1\".
	ApiVersion string `json:"apiVersion,omitempty"`
	// Path of the field to select in the specified API version.
	FieldPath string `json:"fieldPath"`
}
