/*
 * Application Manager API
 *
 * Application Manager APIs to control Apache Flink jobs
 *
 * API version: 2.6.1
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

//+kubebuilder:object:generate=true
type IntOrString struct {
	IntValue int32  `json:"intValue,omitempty"`
	Integer  bool   `json:"integer,omitempty"`
	StrValue string `json:"strValue,omitempty"`
}
