/*
 * Application Manager API
 *
 * Application Manager APIs to control Apache Flink jobs
 *
 * API version: 2.6.1
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	time "k8s.io/apimachinery/pkg/apis/meta/v1"
)

//+kubebuilder:object:generate=true
type EventMetadata struct {
	CreatedAt        time.Time `json:"createdAt,omitempty"`
	DeploymentId     string    `json:"deploymentId,omitempty"`
	Id               string    `json:"id,omitempty"`
	JobId            string    `json:"jobId,omitempty"`
	Name             string    `json:"name,omitempty"`
	Namespace        string    `json:"namespace,omitempty"`
	ResourceName     string    `json:"resourceName,omitempty"`
	ResourceVersion  int32     `json:"resourceVersion,omitempty"`
	SessionClusterId string    `json:"sessionClusterId,omitempty"`
}
