/*
 * Application Manager API
 *
 * Application Manager APIs to control Apache Flink jobs
 *
 * API version: 2.6.1
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type KubernetesOptions struct {
	Labels                 map[string]string  `json:"labels,omitempty"`
	Pods                   *Pods              `json:"pods,omitempty"`
	JobManagerPodTemplate  *V1PodTemplateSpec `json:"jobManagerPodTemplate,omitempty"`
	TaskManagerPodTemplate *V1PodTemplateSpec `json:"taskManagerPodTemplate,omitempty"`
}
