/*
 * Application Manager API
 *
 * Application Manager APIs to control Apache Flink jobs
 *
 * API version: 2.6.1
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// PodDNSConfigOption defines DNS resolver options of a pod.
type V1PodDnsConfigOption struct {
	// Required.
	Name  string `json:"name,omitempty"`
	Value string `json:"value,omitempty"`
}
