# permissions for end users to view apitokens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apitoken-viewer-role
rules:
- apiGroups:
  - platform.vvp.efrat19.io
  resources:
  - apitokens
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.vvp.efrat19.io
  resources:
  - apitokens/status
  verbs:
  - get
