# permissions for end users to edit apitokens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apitoken-editor-role
rules:
- apiGroups:
  - platform.vvp.efrat19.io
  resources:
  - apitokens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.vvp.efrat19.io
  resources:
  - apitokens/status
  verbs:
  - get
