# permissions for end users to edit catalogconnectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: catalogconnectors-editor-role
rules:
- apiGroups:
  - platform.vvp.efrat19.io
  resources:
  - catalogconnectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.vvp.efrat19.io
  resources:
  - catalogconnectors/status
  verbs:
  - get
