# permissions for end users to view deploymenttargets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploymenttarget-viewer-role
rules:
- apiGroups:
  - appmanager.vvp.efrat19.io
  resources:
  - deploymenttargets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appmanager.vvp.efrat19.io
  resources:
  - deploymenttargets/status
  verbs:
  - get
