# permissions for end users to edit deploymentdefaults.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploymentdefaults-editor-role
rules:
- apiGroups:
  - appmanager.vvp.efrat19.io
  resources:
  - deploymentdefaults
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appmanager.vvp.efrat19.io
  resources:
  - deploymentdefaults/status
  verbs:
  - get
