# permissions for end users to edit deploymenttargets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploymenttarget-editor-role
rules:
- apiGroups:
  - appmanager.vvp.efrat19.io
  resources:
  - deploymenttargets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appmanager.vvp.efrat19.io
  resources:
  - deploymenttargets/status
  verbs:
  - get
