# permissions for end users to edit formats.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: format-editor-role
rules:
- apiGroups:
  - platform.vvp.efrat19.io
  resources:
  - formats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.vvp.efrat19.io
  resources:
  - formats/status
  verbs:
  - get
