# permissions for end users to edit savepoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: savepoint-editor-role
rules:
- apiGroups:
  - vvp.appmanager.efrat19.io.efrat19.io
  resources:
  - savepoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vvp.appmanager.efrat19.io.efrat19.io
  resources:
  - savepoints/status
  verbs:
  - get
