# permissions for end users to view savepoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: savepoint-viewer-role
rules:
- apiGroups:
  - vvp.appmanager.efrat19.io.efrat19.io
  resources:
  - savepoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vvp.appmanager.efrat19.io.efrat19.io
  resources:
  - savepoints/status
  verbs:
  - get
