# permissions for end users to view secretvalues.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretvalue-viewer-role
rules:
- apiGroups:
  - vvp.appmanager.efrat19.io.efrat19.io
  resources:
  - secretvalues
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vvp.appmanager.efrat19.io.efrat19.io
  resources:
  - secretvalues/status
  verbs:
  - get
