# permissions for end users to edit secretvalues.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretvalue-editor-role
rules:
- apiGroups:
  - vvp.appmanager.efrat19.io.efrat19.io
  resources:
  - secretvalues
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vvp.appmanager.efrat19.io.efrat19.io
  resources:
  - secretvalues/status
  verbs:
  - get
