# permissions for end users to view sessionclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sessioncluster-viewer-role
rules:
- apiGroups:
  - vvp.appmanager.efrat19.io.efrat19.io
  resources:
  - sessionclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vvp.appmanager.efrat19.io.efrat19.io
  resources:
  - sessionclusters/status
  verbs:
  - get
