# permissions for end users to edit sqlscripts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sqlscripts-editor-role
rules:
- apiGroups:
  - platform.vvp.efrat19.io
  resources:
  - sqlscripts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.vvp.efrat19.io
  resources:
  - sqlscripts/status
  verbs:
  - get
