# permissions for end users to view sqlscripts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sqlscript-viewer-role
rules:
- apiGroups:
  - platform.vvp.efrat19.io
  resources:
  - sqlscripts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.vvp.efrat19.io
  resources:
  - sqlscripts/status
  verbs:
  - get
