# permissions for end users to view udfartifacts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: udfartifact-viewer-role
rules:
- apiGroups:
  - platform.vvp.efrat19.io
  resources:
  - udfartifacts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.vvp.efrat19.io
  resources:
  - udfartifacts/status
  verbs:
  - get
