apiVersion: appmanager.vvp.efrat19.io/v1alpha1
kind: SessionCluster
metadata:
  name: vvp-gitops-operator-example
  namespace: vvp
spec:
  metadata:
    name: vvp-gitops-operator-example
    namespace: vvp
  spec:
    deploymentTargetName: vvp-gitops-operator-example
    flinkVersion: '1.14'
    logging:
      log4j2ConfigurationTemplate: vvp-gitops-operator-example
      log4jLoggers: {}
      loggingProfile: vvp-gitops-operator-exam
    resources: {}
    state: vvp-gitops-operator-example