apiVersion: appmanager.vvp.efrat19.io/v1alpha1
kind: SessionCluster
metadata:
  name: vvp-gitops-operator-example
  namespace: vvp
spec:
  metadata:
    name: vvp-gitops-operator-example
    namespace: vvp
  spec:
    deploymentTargetName: cluster1
    flinkConfiguration:
      slot.request.timeout: '10000'
      taskmanager.numberOfTaskSlots: '32'
    flinkImageRegistry: registry.ververica.com/v2.6
    flinkImageRepository: flink
    flinkImageTag: 1.14.2-stream1-scala_2.12-java8
    flinkVersion: '1.14'
    logging:
      log4jLoggers:
        '': INFO
      loggingProfile: default
    numberOfTaskManagers: 1
    resources:
      jobmanager:
        cpu: 1
        memory: 4g
      taskmanager:
        cpu: 1
        memory: 4g
    state: STOPPED