# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/appmanager.vvp.efrat19.io_deployments.yaml
- bases/appmanager.vvp.efrat19.io_deploymenttargets.yaml
- bases/appmanager.vvp.efrat19.io_savepoints.yaml
- bases/appmanager.vvp.efrat19.io_secretvalues.yaml
- bases/appmanager.vvp.efrat19.io_sessionclusters.yaml
- bases/platform.vvp.efrat19.io_apitoken.yaml
- bases/platform.vvp.efrat19.io_catalogconnector.yaml
- bases/platform.vvp.efrat19.io_connector.yaml
- bases/platform.vvp.efrat19.io_format.yaml
- bases/platform.vvp.efrat19.io_sqlscript.yaml
- bases/platform.vvp.efrat19.io_udfartifact.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_deployments.yaml
#- patches/webhook_in_deploymenttargets.yaml
#- patches/webhook_in_savepoints.yaml
#- patches/webhook_in_secretvalues.yaml
#- patches/webhook_in_sessionclusters.yaml
#- patches/webhook_in_apitoken.yaml
#- patches/webhook_in_catalogconnector.yaml
#- patches/webhook_in_connector.yaml
#- patches/webhook_in_format.yaml
#- patches/webhook_in_sqlscript.yaml
#- patches/webhook_in_udfartifact.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_deployments.yaml
#- patches/cainjection_in_deploymenttargets.yaml
#- patches/cainjection_in_savepoints.yaml
#- patches/cainjection_in_secretvalues.yaml
#- patches/cainjection_in_sessionclusters.yaml
#- patches/cainjection_in_apitoken.yaml
#- patches/cainjection_in_catalogconnector.yaml
#- patches/cainjection_in_connector.yaml
#- patches/cainjection_in_format.yaml
#- patches/cainjection_in_sqlscript.yaml
#- patches/cainjection_in_udfartifact.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
