/*
 * Ververica Platform API
 *
 * The Ververica Platform APIs, excluding Application Manager.
 *
 * API version: 2.6.1
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type VvpTable struct {
	Comment string `json:"comment,omitempty"`
	Name string `json:"name,omitempty"`
	Properties map[string]string `json:"properties,omitempty"`
	Schema *VvpSchema `json:"schema,omitempty"`
}
