/*
 * Ververica Platform API
 *
 * The Ververica Platform APIs, excluding Application Manager.
 *
 * API version: 2.6.1
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ValidateStatementResponse struct {
	ErrorDetails     *ErrorDetails `json:"errorDetails,omitempty"`
	ValidationResult string        `json:"validationResult,omitempty"`
}
