/*
 * Ververica Platform API
 *
 * The Ververica Platform APIs, excluding Application Manager.
 *
 * API version: 2.6.1
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AutoscalerConfig struct {
	CooldownMinutes   int32             `json:"cooldownMinutes,omitempty"`
	ExtraConfig       map[string]string `json:"extraConfig,omitempty"`
	MaxParallelism    int32             `json:"maxParallelism,omitempty"`
	MinParallelism    int32             `json:"minParallelism,omitempty"`
	TargetUtilization int32             `json:"targetUtilization,omitempty"`
}
