/*
 * Ververica Platform API
 *
 * The Ververica Platform APIs, excluding Application Manager.
 *
 * API version: 2.6.1
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UdfClass struct {
	ClassName       string   `json:"className,omitempty"`
	ClassType       string   `json:"classType,omitempty"`
	FunctionNames   []string `json:"functionNames,omitempty"`
	UdfArtifactName string   `json:"udfArtifactName,omitempty"`
}
