/*
 * Ververica Platform API
 *
 * The Ververica Platform APIs, excluding Application Manager.
 *
 * API version: 2.6.1
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

//+kubebuilder:object:generate=true
type AutoscalingSourceStatus struct {
	Capacity                float64 `json:"capacity,omitempty"`
	EstimatedCatchUpSeconds int32   `json:"estimatedCatchUpSeconds,omitempty"`
	EstimatedLagSeconds     int32   `json:"estimatedLagSeconds,omitempty"`
	Target                  float64 `json:"target,omitempty"`
	TaskName                string  `json:"taskName,omitempty"`
	Throughput              float64 `json:"throughput,omitempty"`
	VertexId                string  `json:"vertexId,omitempty"`
}
