/*
 * Ververica Platform API
 *
 * The Ververica Platform APIs, excluding Application Manager.
 *
 * API version: 2.6.1
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type VvpSchema struct {
	Column []VvpColumn `json:"column,omitempty"`
	PrimaryKey *VvpUniqueConstraint `json:"primaryKey,omitempty"`
	WatermarkSpec []VvpWatermark `json:"watermarkSpec,omitempty"`
}
