//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package swagger

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyzeCatalogConnectorJarsResponse) DeepCopyInto(out *AnalyzeCatalogConnectorJarsResponse) {
	*out = *in
	if in.CatalogConnectors != nil {
		in, out := &in.CatalogConnectors, &out.CatalogConnectors
		*out = make([]CatalogConnector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyzeCatalogConnectorJarsResponse.
func (in *AnalyzeCatalogConnectorJarsResponse) DeepCopy() *AnalyzeCatalogConnectorJarsResponse {
	if in == nil {
		return nil
	}
	out := new(AnalyzeCatalogConnectorJarsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiToken) DeepCopyInto(out *ApiToken) {
	*out = *in
	in.CreateTime.DeepCopyInto(&out.CreateTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiToken.
func (in *ApiToken) DeepCopy() *ApiToken {
	if in == nil {
		return nil
	}
	out := new(ApiToken)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutopilotPolicy) DeepCopyInto(out *AutopilotPolicy) {
	*out = *in
	if in.AutoscalerConfig != nil {
		in, out := &in.AutoscalerConfig, &out.AutoscalerConfig
		*out = new(AutoscalerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.LibraConfig != nil {
		in, out := &in.LibraConfig, &out.LibraConfig
		*out = new(LibraConfig)
		(*in).DeepCopyInto(*out)
	}
	in.ModifyTime.DeepCopyInto(&out.ModifyTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutopilotPolicy.
func (in *AutopilotPolicy) DeepCopy() *AutopilotPolicy {
	if in == nil {
		return nil
	}
	out := new(AutopilotPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutopilotPolicyRecommendation) DeepCopyInto(out *AutopilotPolicyRecommendation) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutopilotPolicyRecommendation.
func (in *AutopilotPolicyRecommendation) DeepCopy() *AutopilotPolicyRecommendation {
	if in == nil {
		return nil
	}
	out := new(AutopilotPolicyRecommendation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutopilotPolicyStatus) DeepCopyInto(out *AutopilotPolicyStatus) {
	*out = *in
	if in.AutoscalerStatus != nil {
		in, out := &in.AutoscalerStatus, &out.AutoscalerStatus
		*out = new(AutoscalerStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LibraStatus != nil {
		in, out := &in.LibraStatus, &out.LibraStatus
		*out = new(LibraStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutopilotPolicyStatus.
func (in *AutopilotPolicyStatus) DeepCopy() *AutopilotPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AutopilotPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalerConfig) DeepCopyInto(out *AutoscalerConfig) {
	*out = *in
	if in.ExtraConfig != nil {
		in, out := &in.ExtraConfig, &out.ExtraConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalerConfig.
func (in *AutoscalerConfig) DeepCopy() *AutoscalerConfig {
	if in == nil {
		return nil
	}
	out := new(AutoscalerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalerStatus) DeepCopyInto(out *AutoscalerStatus) {
	*out = *in
	in.LastActionTime.DeepCopyInto(&out.LastActionTime)
	if in.SourceStatus != nil {
		in, out := &in.SourceStatus, &out.SourceStatus
		*out = make([]AutoscalingSourceStatus, len(*in))
		copy(*out, *in)
	}
	in.UpdateTime.DeepCopyInto(&out.UpdateTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalerStatus.
func (in *AutoscalerStatus) DeepCopy() *AutoscalerStatus {
	if in == nil {
		return nil
	}
	out := new(AutoscalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingSourceStatus) DeepCopyInto(out *AutoscalingSourceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingSourceStatus.
func (in *AutoscalingSourceStatus) DeepCopy() *AutoscalingSourceStatus {
	if in == nil {
		return nil
	}
	out := new(AutoscalingSourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Catalog) DeepCopyInto(out *Catalog) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Catalog.
func (in *Catalog) DeepCopy() *Catalog {
	if in == nil {
		return nil
	}
	out := new(Catalog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogConnector) DeepCopyInto(out *CatalogConnector) {
	*out = *in
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make([]Property, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogConnector.
func (in *CatalogConnector) DeepCopy() *CatalogConnector {
	if in == nil {
		return nil
	}
	out := new(CatalogConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogReference) DeepCopyInto(out *CatalogReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogReference.
func (in *CatalogReference) DeepCopy() *CatalogReference {
	if in == nil {
		return nil
	}
	out := new(CatalogReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSpec) DeepCopyInto(out *ConfigSpec) {
	*out = *in
	if in.NewConfig != nil {
		in, out := &in.NewConfig, &out.NewConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSpec.
func (in *ConfigSpec) DeepCopy() *ConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Connector) DeepCopyInto(out *Connector) {
	*out = *in
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make([]Property, len(*in))
		copy(*out, *in)
	}
	if in.SupportedFormats != nil {
		in, out := &in.SupportedFormats, &out.SupportedFormats
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Connector.
func (in *Connector) DeepCopy() *Connector {
	if in == nil {
		return nil
	}
	out := new(Connector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateApiTokenResponse) DeepCopyInto(out *CreateApiTokenResponse) {
	*out = *in
	if in.ApiToken != nil {
		in, out := &in.ApiToken, &out.ApiToken
		*out = new(ApiToken)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateApiTokenResponse.
func (in *CreateApiTokenResponse) DeepCopy() *CreateApiTokenResponse {
	if in == nil {
		return nil
	}
	out := new(CreateApiTokenResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateCatalogConnectorResponse) DeepCopyInto(out *CreateCatalogConnectorResponse) {
	*out = *in
	if in.CatalogConnector != nil {
		in, out := &in.CatalogConnector, &out.CatalogConnector
		*out = new(CatalogConnector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateCatalogConnectorResponse.
func (in *CreateCatalogConnectorResponse) DeepCopy() *CreateCatalogConnectorResponse {
	if in == nil {
		return nil
	}
	out := new(CreateCatalogConnectorResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateConnectorResponse) DeepCopyInto(out *CreateConnectorResponse) {
	*out = *in
	if in.Connector != nil {
		in, out := &in.Connector, &out.Connector
		*out = new(Connector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateConnectorResponse.
func (in *CreateConnectorResponse) DeepCopy() *CreateConnectorResponse {
	if in == nil {
		return nil
	}
	out := new(CreateConnectorResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateFormatResponse) DeepCopyInto(out *CreateFormatResponse) {
	*out = *in
	if in.Format != nil {
		in, out := &in.Format, &out.Format
		*out = new(Format)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateFormatResponse.
func (in *CreateFormatResponse) DeepCopy() *CreateFormatResponse {
	if in == nil {
		return nil
	}
	out := new(CreateFormatResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateJobGraphResponse) DeepCopyInto(out *CreateJobGraphResponse) {
	*out = *in
	if in.Jobgraph != nil {
		in, out := &in.Jobgraph, &out.Jobgraph
		*out = new(JobGraph)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateJobGraphResponse.
func (in *CreateJobGraphResponse) DeepCopy() *CreateJobGraphResponse {
	if in == nil {
		return nil
	}
	out := new(CreateJobGraphResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateNamespaceResponse) DeepCopyInto(out *CreateNamespaceResponse) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(Namespace)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateNamespaceResponse.
func (in *CreateNamespaceResponse) DeepCopy() *CreateNamespaceResponse {
	if in == nil {
		return nil
	}
	out := new(CreateNamespaceResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateSqlScriptResponse) DeepCopyInto(out *CreateSqlScriptResponse) {
	*out = *in
	if in.SqlScript != nil {
		in, out := &in.SqlScript, &out.SqlScript
		*out = new(SqlScript)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateSqlScriptResponse.
func (in *CreateSqlScriptResponse) DeepCopy() *CreateSqlScriptResponse {
	if in == nil {
		return nil
	}
	out := new(CreateSqlScriptResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateUdfArtifactResponse) DeepCopyInto(out *CreateUdfArtifactResponse) {
	*out = *in
	if in.CollidingClasses != nil {
		in, out := &in.CollidingClasses, &out.CollidingClasses
		*out = make([]UdfClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UdfArtifact != nil {
		in, out := &in.UdfArtifact, &out.UdfArtifact
		*out = new(UdfArtifact)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateUdfArtifactResponse.
func (in *CreateUdfArtifactResponse) DeepCopy() *CreateUdfArtifactResponse {
	if in == nil {
		return nil
	}
	out := new(CreateUdfArtifactResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Database) DeepCopyInto(out *Database) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Database.
func (in *Database) DeepCopy() *Database {
	if in == nil {
		return nil
	}
	out := new(Database)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteApiTokenResponse) DeepCopyInto(out *DeleteApiTokenResponse) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteApiTokenResponse.
func (in *DeleteApiTokenResponse) DeepCopy() *DeleteApiTokenResponse {
	if in == nil {
		return nil
	}
	out := new(DeleteApiTokenResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteCatalogConnectorResponse) DeepCopyInto(out *DeleteCatalogConnectorResponse) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteCatalogConnectorResponse.
func (in *DeleteCatalogConnectorResponse) DeepCopy() *DeleteCatalogConnectorResponse {
	if in == nil {
		return nil
	}
	out := new(DeleteCatalogConnectorResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteConnectorResponse) DeepCopyInto(out *DeleteConnectorResponse) {
	*out = *in
	if in.AffectedTables != nil {
		in, out := &in.AffectedTables, &out.AffectedTables
		*out = make([]TableReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteConnectorResponse.
func (in *DeleteConnectorResponse) DeepCopy() *DeleteConnectorResponse {
	if in == nil {
		return nil
	}
	out := new(DeleteConnectorResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteFormatResponse) DeepCopyInto(out *DeleteFormatResponse) {
	*out = *in
	if in.AffectedTables != nil {
		in, out := &in.AffectedTables, &out.AffectedTables
		*out = make([]TableReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteFormatResponse.
func (in *DeleteFormatResponse) DeepCopy() *DeleteFormatResponse {
	if in == nil {
		return nil
	}
	out := new(DeleteFormatResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteJobGraphResponse) DeepCopyInto(out *DeleteJobGraphResponse) {
	*out = *in
	if in.NotDeletedFiles != nil {
		in, out := &in.NotDeletedFiles, &out.NotDeletedFiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteJobGraphResponse.
func (in *DeleteJobGraphResponse) DeepCopy() *DeleteJobGraphResponse {
	if in == nil {
		return nil
	}
	out := new(DeleteJobGraphResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteJobGraphsResponse) DeepCopyInto(out *DeleteJobGraphsResponse) {
	*out = *in
	if in.DeletedJobGraphs != nil {
		in, out := &in.DeletedJobGraphs, &out.DeletedJobGraphs
		*out = make([]DeleteJobGraphResponse, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteJobGraphsResponse.
func (in *DeleteJobGraphsResponse) DeepCopy() *DeleteJobGraphsResponse {
	if in == nil {
		return nil
	}
	out := new(DeleteJobGraphsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteNamespaceResponse) DeepCopyInto(out *DeleteNamespaceResponse) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(Namespace)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteNamespaceResponse.
func (in *DeleteNamespaceResponse) DeepCopy() *DeleteNamespaceResponse {
	if in == nil {
		return nil
	}
	out := new(DeleteNamespaceResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteSqlScriptResponse) DeepCopyInto(out *DeleteSqlScriptResponse) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteSqlScriptResponse.
func (in *DeleteSqlScriptResponse) DeepCopy() *DeleteSqlScriptResponse {
	if in == nil {
		return nil
	}
	out := new(DeleteSqlScriptResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteUdfArtifactResponse) DeepCopyInto(out *DeleteUdfArtifactResponse) {
	*out = *in
	if in.ReferencedClasses != nil {
		in, out := &in.ReferencedClasses, &out.ReferencedClasses
		*out = make([]UdfClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteUdfArtifactResponse.
func (in *DeleteUdfArtifactResponse) DeepCopy() *DeleteUdfArtifactResponse {
	if in == nil {
		return nil
	}
	out := new(DeleteUdfArtifactResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ErrorDetails) DeepCopyInto(out *ErrorDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ErrorDetails.
func (in *ErrorDetails) DeepCopy() *ErrorDetails {
	if in == nil {
		return nil
	}
	out := new(ErrorDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecuteStatementResponse) DeepCopyInto(out *ExecuteStatementResponse) {
	*out = *in
	if in.ErrorMessage != nil {
		in, out := &in.ErrorMessage, &out.ErrorMessage
		*out = new(ErrorDetails)
		**out = **in
	}
	if in.ResultTable != nil {
		in, out := &in.ResultTable, &out.ResultTable
		*out = new(ResultTable)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecuteStatementResponse.
func (in *ExecuteStatementResponse) DeepCopy() *ExecuteStatementResponse {
	if in == nil {
		return nil
	}
	out := new(ExecuteStatementResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecuteStatementsResponse) DeepCopyInto(out *ExecuteStatementsResponse) {
	*out = *in
	if in.Responses != nil {
		in, out := &in.Responses, &out.Responses
		*out = make([]ExecuteStatementResponse, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecuteStatementsResponse.
func (in *ExecuteStatementsResponse) DeepCopy() *ExecuteStatementsResponse {
	if in == nil {
		return nil
	}
	out := new(ExecuteStatementsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Format) DeepCopyInto(out *Format) {
	*out = *in
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make([]Property, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Format.
func (in *Format) DeepCopy() *Format {
	if in == nil {
		return nil
	}
	out := new(Format)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Function) DeepCopyInto(out *Function) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Function.
func (in *Function) DeepCopy() *Function {
	if in == nil {
		return nil
	}
	out := new(Function)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetApiTokenResponse) DeepCopyInto(out *GetApiTokenResponse) {
	*out = *in
	if in.ApiToken != nil {
		in, out := &in.ApiToken, &out.ApiToken
		*out = new(ApiToken)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetApiTokenResponse.
func (in *GetApiTokenResponse) DeepCopy() *GetApiTokenResponse {
	if in == nil {
		return nil
	}
	out := new(GetApiTokenResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetAutopilotPolicyRecommendationResponse) DeepCopyInto(out *GetAutopilotPolicyRecommendationResponse) {
	*out = *in
	if in.Recommendation != nil {
		in, out := &in.Recommendation, &out.Recommendation
		*out = new(AutopilotPolicyRecommendation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetAutopilotPolicyRecommendationResponse.
func (in *GetAutopilotPolicyRecommendationResponse) DeepCopy() *GetAutopilotPolicyRecommendationResponse {
	if in == nil {
		return nil
	}
	out := new(GetAutopilotPolicyRecommendationResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetAutopilotPolicyResponse) DeepCopyInto(out *GetAutopilotPolicyResponse) {
	*out = *in
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(AutopilotPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetAutopilotPolicyResponse.
func (in *GetAutopilotPolicyResponse) DeepCopy() *GetAutopilotPolicyResponse {
	if in == nil {
		return nil
	}
	out := new(GetAutopilotPolicyResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetAutopilotPolicyStatusResponse) DeepCopyInto(out *GetAutopilotPolicyStatusResponse) {
	*out = *in
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(AutopilotPolicyStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetAutopilotPolicyStatusResponse.
func (in *GetAutopilotPolicyStatusResponse) DeepCopy() *GetAutopilotPolicyStatusResponse {
	if in == nil {
		return nil
	}
	out := new(GetAutopilotPolicyStatusResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetCatalogConnectorResponse) DeepCopyInto(out *GetCatalogConnectorResponse) {
	*out = *in
	if in.CatalogConnector != nil {
		in, out := &in.CatalogConnector, &out.CatalogConnector
		*out = new(CatalogConnector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetCatalogConnectorResponse.
func (in *GetCatalogConnectorResponse) DeepCopy() *GetCatalogConnectorResponse {
	if in == nil {
		return nil
	}
	out := new(GetCatalogConnectorResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetCatalogResponse) DeepCopyInto(out *GetCatalogResponse) {
	*out = *in
	if in.Catalog != nil {
		in, out := &in.Catalog, &out.Catalog
		*out = new(Catalog)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetCatalogResponse.
func (in *GetCatalogResponse) DeepCopy() *GetCatalogResponse {
	if in == nil {
		return nil
	}
	out := new(GetCatalogResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetConnectorResponse) DeepCopyInto(out *GetConnectorResponse) {
	*out = *in
	if in.Connector != nil {
		in, out := &in.Connector, &out.Connector
		*out = new(Connector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetConnectorResponse.
func (in *GetConnectorResponse) DeepCopy() *GetConnectorResponse {
	if in == nil {
		return nil
	}
	out := new(GetConnectorResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetDatabaseResponse) DeepCopyInto(out *GetDatabaseResponse) {
	*out = *in
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(Database)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetDatabaseResponse.
func (in *GetDatabaseResponse) DeepCopy() *GetDatabaseResponse {
	if in == nil {
		return nil
	}
	out := new(GetDatabaseResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetFormatResponse) DeepCopyInto(out *GetFormatResponse) {
	*out = *in
	if in.Format != nil {
		in, out := &in.Format, &out.Format
		*out = new(Format)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetFormatResponse.
func (in *GetFormatResponse) DeepCopy() *GetFormatResponse {
	if in == nil {
		return nil
	}
	out := new(GetFormatResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetFunctionResponse) DeepCopyInto(out *GetFunctionResponse) {
	*out = *in
	if in.Function != nil {
		in, out := &in.Function, &out.Function
		*out = new(Function)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetFunctionResponse.
func (in *GetFunctionResponse) DeepCopy() *GetFunctionResponse {
	if in == nil {
		return nil
	}
	out := new(GetFunctionResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetNamespaceResponse) DeepCopyInto(out *GetNamespaceResponse) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(Namespace)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetNamespaceResponse.
func (in *GetNamespaceResponse) DeepCopy() *GetNamespaceResponse {
	if in == nil {
		return nil
	}
	out := new(GetNamespaceResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetSqlScriptResponse) DeepCopyInto(out *GetSqlScriptResponse) {
	*out = *in
	if in.SqlScript != nil {
		in, out := &in.SqlScript, &out.SqlScript
		*out = new(SqlScript)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetSqlScriptResponse.
func (in *GetSqlScriptResponse) DeepCopy() *GetSqlScriptResponse {
	if in == nil {
		return nil
	}
	out := new(GetSqlScriptResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetTableResponse) DeepCopyInto(out *GetTableResponse) {
	*out = *in
	if in.Table != nil {
		in, out := &in.Table, &out.Table
		*out = new(VvpTable)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetTableResponse.
func (in *GetTableResponse) DeepCopy() *GetTableResponse {
	if in == nil {
		return nil
	}
	out := new(GetTableResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetUdfArtifactResponse) DeepCopyInto(out *GetUdfArtifactResponse) {
	*out = *in
	if in.UdfArtifact != nil {
		in, out := &in.UdfArtifact, &out.UdfArtifact
		*out = new(UdfArtifact)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetUdfArtifactResponse.
func (in *GetUdfArtifactResponse) DeepCopy() *GetUdfArtifactResponse {
	if in == nil {
		return nil
	}
	out := new(GetUdfArtifactResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetViewResponse) DeepCopyInto(out *GetViewResponse) {
	*out = *in
	if in.View != nil {
		in, out := &in.View, &out.View
		*out = new(VvpView)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetViewResponse.
func (in *GetViewResponse) DeepCopy() *GetViewResponse {
	if in == nil {
		return nil
	}
	out := new(GetViewResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JarUri) DeepCopyInto(out *JarUri) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JarUri.
func (in *JarUri) DeepCopy() *JarUri {
	if in == nil {
		return nil
	}
	out := new(JarUri)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JarUris) DeepCopyInto(out *JarUris) {
	*out = *in
	if in.JarUris != nil {
		in, out := &in.JarUris, &out.JarUris
		*out = make([]JarUri, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JarUris.
func (in *JarUris) DeepCopy() *JarUris {
	if in == nil {
		return nil
	}
	out := new(JarUris)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobGraph) DeepCopyInto(out *JobGraph) {
	*out = *in
	in.CreateTime.DeepCopyInto(&out.CreateTime)
	if in.ErrorDetails != nil {
		in, out := &in.ErrorDetails, &out.ErrorDetails
		*out = new(ErrorDetails)
		**out = **in
	}
	if in.FullFlinkConfiguration != nil {
		in, out := &in.FullFlinkConfiguration, &out.FullFlinkConfiguration
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.JarUris != nil {
		in, out := &in.JarUris, &out.JarUris
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SinkTables != nil {
		in, out := &in.SinkTables, &out.SinkTables
		*out = make([]ReferencedTable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SourceTables != nil {
		in, out := &in.SourceTables, &out.SourceTables
		*out = make([]ReferencedTable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.UpdateTime.DeepCopyInto(&out.UpdateTime)
	if in.UserFlinkConfiguration != nil {
		in, out := &in.UserFlinkConfiguration, &out.UserFlinkConfiguration
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobGraph.
func (in *JobGraph) DeepCopy() *JobGraph {
	if in == nil {
		return nil
	}
	out := new(JobGraph)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobGraphSpec) DeepCopyInto(out *JobGraphSpec) {
	*out = *in
	if in.FullFlinkConfiguration != nil {
		in, out := &in.FullFlinkConfiguration, &out.FullFlinkConfiguration
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.UserFlinkConfiguration != nil {
		in, out := &in.UserFlinkConfiguration, &out.UserFlinkConfiguration
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobGraphSpec.
func (in *JobGraphSpec) DeepCopy() *JobGraphSpec {
	if in == nil {
		return nil
	}
	out := new(JobGraphSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LibraConfig) DeepCopyInto(out *LibraConfig) {
	*out = *in
	if in.ExtraConfig != nil {
		in, out := &in.ExtraConfig, &out.ExtraConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LibraConfig.
func (in *LibraConfig) DeepCopy() *LibraConfig {
	if in == nil {
		return nil
	}
	out := new(LibraConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LibraStatus) DeepCopyInto(out *LibraStatus) {
	*out = *in
	in.LastActionTime.DeepCopyInto(&out.LastActionTime)
	in.UpdateTime.DeepCopyInto(&out.UpdateTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LibraStatus.
func (in *LibraStatus) DeepCopy() *LibraStatus {
	if in == nil {
		return nil
	}
	out := new(LibraStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListApiTokensResponse) DeepCopyInto(out *ListApiTokensResponse) {
	*out = *in
	if in.ApiTokens != nil {
		in, out := &in.ApiTokens, &out.ApiTokens
		*out = make([]ApiToken, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListApiTokensResponse.
func (in *ListApiTokensResponse) DeepCopy() *ListApiTokensResponse {
	if in == nil {
		return nil
	}
	out := new(ListApiTokensResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListAutopilotPoliciesResponse) DeepCopyInto(out *ListAutopilotPoliciesResponse) {
	*out = *in
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]AutopilotPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListAutopilotPoliciesResponse.
func (in *ListAutopilotPoliciesResponse) DeepCopy() *ListAutopilotPoliciesResponse {
	if in == nil {
		return nil
	}
	out := new(ListAutopilotPoliciesResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListCatalogConnectorsResponse) DeepCopyInto(out *ListCatalogConnectorsResponse) {
	*out = *in
	if in.CatalogConnectors != nil {
		in, out := &in.CatalogConnectors, &out.CatalogConnectors
		*out = make([]CatalogConnector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListCatalogConnectorsResponse.
func (in *ListCatalogConnectorsResponse) DeepCopy() *ListCatalogConnectorsResponse {
	if in == nil {
		return nil
	}
	out := new(ListCatalogConnectorsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListCatalogsReferencingCatalogConnectorResponse) DeepCopyInto(out *ListCatalogsReferencingCatalogConnectorResponse) {
	*out = *in
	if in.Catalogs != nil {
		in, out := &in.Catalogs, &out.Catalogs
		*out = make([]CatalogReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListCatalogsReferencingCatalogConnectorResponse.
func (in *ListCatalogsReferencingCatalogConnectorResponse) DeepCopy() *ListCatalogsReferencingCatalogConnectorResponse {
	if in == nil {
		return nil
	}
	out := new(ListCatalogsReferencingCatalogConnectorResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListCatalogsResponse) DeepCopyInto(out *ListCatalogsResponse) {
	*out = *in
	if in.Catalogs != nil {
		in, out := &in.Catalogs, &out.Catalogs
		*out = make([]Catalog, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListCatalogsResponse.
func (in *ListCatalogsResponse) DeepCopy() *ListCatalogsResponse {
	if in == nil {
		return nil
	}
	out := new(ListCatalogsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListConnectorsResponse) DeepCopyInto(out *ListConnectorsResponse) {
	*out = *in
	if in.Connectors != nil {
		in, out := &in.Connectors, &out.Connectors
		*out = make([]Connector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListConnectorsResponse.
func (in *ListConnectorsResponse) DeepCopy() *ListConnectorsResponse {
	if in == nil {
		return nil
	}
	out := new(ListConnectorsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListDatabasesResponse) DeepCopyInto(out *ListDatabasesResponse) {
	*out = *in
	if in.Databases != nil {
		in, out := &in.Databases, &out.Databases
		*out = make([]Database, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListDatabasesResponse.
func (in *ListDatabasesResponse) DeepCopy() *ListDatabasesResponse {
	if in == nil {
		return nil
	}
	out := new(ListDatabasesResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListFormatsResponse) DeepCopyInto(out *ListFormatsResponse) {
	*out = *in
	if in.Formats != nil {
		in, out := &in.Formats, &out.Formats
		*out = make([]Format, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListFormatsResponse.
func (in *ListFormatsResponse) DeepCopy() *ListFormatsResponse {
	if in == nil {
		return nil
	}
	out := new(ListFormatsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListFunctionsResponse) DeepCopyInto(out *ListFunctionsResponse) {
	*out = *in
	if in.Functions != nil {
		in, out := &in.Functions, &out.Functions
		*out = make([]Function, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListFunctionsResponse.
func (in *ListFunctionsResponse) DeepCopy() *ListFunctionsResponse {
	if in == nil {
		return nil
	}
	out := new(ListFunctionsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListNamespacesResponse) DeepCopyInto(out *ListNamespacesResponse) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]Namespace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListNamespacesResponse.
func (in *ListNamespacesResponse) DeepCopy() *ListNamespacesResponse {
	if in == nil {
		return nil
	}
	out := new(ListNamespacesResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListSqlScriptsResponse) DeepCopyInto(out *ListSqlScriptsResponse) {
	*out = *in
	if in.SqlScripts != nil {
		in, out := &in.SqlScripts, &out.SqlScripts
		*out = make([]SqlScript, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListSqlScriptsResponse.
func (in *ListSqlScriptsResponse) DeepCopy() *ListSqlScriptsResponse {
	if in == nil {
		return nil
	}
	out := new(ListSqlScriptsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListTablesReferencingConnectorResponse) DeepCopyInto(out *ListTablesReferencingConnectorResponse) {
	*out = *in
	if in.Tables != nil {
		in, out := &in.Tables, &out.Tables
		*out = make([]TableReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListTablesReferencingConnectorResponse.
func (in *ListTablesReferencingConnectorResponse) DeepCopy() *ListTablesReferencingConnectorResponse {
	if in == nil {
		return nil
	}
	out := new(ListTablesReferencingConnectorResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListTablesReferencingFormatResponse) DeepCopyInto(out *ListTablesReferencingFormatResponse) {
	*out = *in
	if in.Tables != nil {
		in, out := &in.Tables, &out.Tables
		*out = make([]TableReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListTablesReferencingFormatResponse.
func (in *ListTablesReferencingFormatResponse) DeepCopy() *ListTablesReferencingFormatResponse {
	if in == nil {
		return nil
	}
	out := new(ListTablesReferencingFormatResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListTablesResponse) DeepCopyInto(out *ListTablesResponse) {
	*out = *in
	if in.Tables != nil {
		in, out := &in.Tables, &out.Tables
		*out = make([]VvpTable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListTablesResponse.
func (in *ListTablesResponse) DeepCopy() *ListTablesResponse {
	if in == nil {
		return nil
	}
	out := new(ListTablesResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListUdfArtifactsResponse) DeepCopyInto(out *ListUdfArtifactsResponse) {
	*out = *in
	if in.UdfArtifacts != nil {
		in, out := &in.UdfArtifacts, &out.UdfArtifacts
		*out = make([]UdfArtifact, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListUdfArtifactsResponse.
func (in *ListUdfArtifactsResponse) DeepCopy() *ListUdfArtifactsResponse {
	if in == nil {
		return nil
	}
	out := new(ListUdfArtifactsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListViewsResponse) DeepCopyInto(out *ListViewsResponse) {
	*out = *in
	if in.Views != nil {
		in, out := &in.Views, &out.Views
		*out = make([]VvpView, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListViewsResponse.
func (in *ListViewsResponse) DeepCopy() *ListViewsResponse {
	if in == nil {
		return nil
	}
	out := new(ListViewsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Namespace) DeepCopyInto(out *Namespace) {
	*out = *in
	in.CreateTime.DeepCopyInto(&out.CreateTime)
	if in.RoleBindings != nil {
		in, out := &in.RoleBindings, &out.RoleBindings
		*out = make([]RoleBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Namespace.
func (in *Namespace) DeepCopy() *Namespace {
	if in == nil {
		return nil
	}
	out := new(Namespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Property) DeepCopyInto(out *Property) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Property.
func (in *Property) DeepCopy() *Property {
	if in == nil {
		return nil
	}
	out := new(Property)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReferencedTable) DeepCopyInto(out *ReferencedTable) {
	*out = *in
	if in.Table != nil {
		in, out := &in.Table, &out.Table
		*out = new(VvpTable)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReferencedTable.
func (in *ReferencedTable) DeepCopy() *ReferencedTable {
	if in == nil {
		return nil
	}
	out := new(ReferencedTable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResultTable) DeepCopyInto(out *ResultTable) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]TableHeader, len(*in))
		copy(*out, *in)
	}
	if in.Rows != nil {
		in, out := &in.Rows, &out.Rows
		*out = make([]TableRow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResultTable.
func (in *ResultTable) DeepCopy() *ResultTable {
	if in == nil {
		return nil
	}
	out := new(ResultTable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleBinding) DeepCopyInto(out *RoleBinding) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleBinding.
func (in *RoleBinding) DeepCopy() *RoleBinding {
	if in == nil {
		return nil
	}
	out := new(RoleBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SetPreviewSessionClusterRequest) DeepCopyInto(out *SetPreviewSessionClusterRequest) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SetPreviewSessionClusterRequest.
func (in *SetPreviewSessionClusterRequest) DeepCopy() *SetPreviewSessionClusterRequest {
	if in == nil {
		return nil
	}
	out := new(SetPreviewSessionClusterRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SetPreviewSessionClusterResponse) DeepCopyInto(out *SetPreviewSessionClusterResponse) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SetPreviewSessionClusterResponse.
func (in *SetPreviewSessionClusterResponse) DeepCopy() *SetPreviewSessionClusterResponse {
	if in == nil {
		return nil
	}
	out := new(SetPreviewSessionClusterResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqlScript) DeepCopyInto(out *SqlScript) {
	*out = *in
	in.CreateTime.DeepCopyInto(&out.CreateTime)
	in.UpdateTime.DeepCopyInto(&out.UpdateTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqlScript.
func (in *SqlScript) DeepCopy() *SqlScript {
	if in == nil {
		return nil
	}
	out := new(SqlScript)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqlScriptCompletion) DeepCopyInto(out *SqlScriptCompletion) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqlScriptCompletion.
func (in *SqlScriptCompletion) DeepCopy() *SqlScriptCompletion {
	if in == nil {
		return nil
	}
	out := new(SqlScriptCompletion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Statement) DeepCopyInto(out *Statement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Statement.
func (in *Statement) DeepCopy() *Statement {
	if in == nil {
		return nil
	}
	out := new(Statement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuggestSqlScriptCompletionsDetails) DeepCopyInto(out *SuggestSqlScriptCompletionsDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuggestSqlScriptCompletionsDetails.
func (in *SuggestSqlScriptCompletionsDetails) DeepCopy() *SuggestSqlScriptCompletionsDetails {
	if in == nil {
		return nil
	}
	out := new(SuggestSqlScriptCompletionsDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuggestSqlScriptCompletionsResponse) DeepCopyInto(out *SuggestSqlScriptCompletionsResponse) {
	*out = *in
	if in.Completions != nil {
		in, out := &in.Completions, &out.Completions
		*out = make([]SqlScriptCompletion, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuggestSqlScriptCompletionsResponse.
func (in *SuggestSqlScriptCompletionsResponse) DeepCopy() *SuggestSqlScriptCompletionsResponse {
	if in == nil {
		return nil
	}
	out := new(SuggestSqlScriptCompletionsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableCell) DeepCopyInto(out *TableCell) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableCell.
func (in *TableCell) DeepCopy() *TableCell {
	if in == nil {
		return nil
	}
	out := new(TableCell)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableHeader) DeepCopyInto(out *TableHeader) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableHeader.
func (in *TableHeader) DeepCopy() *TableHeader {
	if in == nil {
		return nil
	}
	out := new(TableHeader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableReference) DeepCopyInto(out *TableReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableReference.
func (in *TableReference) DeepCopy() *TableReference {
	if in == nil {
		return nil
	}
	out := new(TableReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableRow) DeepCopyInto(out *TableRow) {
	*out = *in
	if in.Cells != nil {
		in, out := &in.Cells, &out.Cells
		*out = make([]TableCell, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableRow.
func (in *TableRow) DeepCopy() *TableRow {
	if in == nil {
		return nil
	}
	out := new(TableRow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UdfArtifact) DeepCopyInto(out *UdfArtifact) {
	*out = *in
	in.CreateTime.DeepCopyInto(&out.CreateTime)
	in.JarUpdateTime.DeepCopyInto(&out.JarUpdateTime)
	if in.UdfClasses != nil {
		in, out := &in.UdfClasses, &out.UdfClasses
		*out = make([]UdfClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.UpdateTime.DeepCopyInto(&out.UpdateTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UdfArtifact.
func (in *UdfArtifact) DeepCopy() *UdfArtifact {
	if in == nil {
		return nil
	}
	out := new(UdfArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UdfClass) DeepCopyInto(out *UdfClass) {
	*out = *in
	if in.FunctionNames != nil {
		in, out := &in.FunctionNames, &out.FunctionNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UdfClass.
func (in *UdfClass) DeepCopy() *UdfClass {
	if in == nil {
		return nil
	}
	out := new(UdfClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateAutopilotPolicyResponse) DeepCopyInto(out *UpdateAutopilotPolicyResponse) {
	*out = *in
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(AutopilotPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateAutopilotPolicyResponse.
func (in *UpdateAutopilotPolicyResponse) DeepCopy() *UpdateAutopilotPolicyResponse {
	if in == nil {
		return nil
	}
	out := new(UpdateAutopilotPolicyResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateCatalogConnectorResponse) DeepCopyInto(out *UpdateCatalogConnectorResponse) {
	*out = *in
	if in.CatalogConnector != nil {
		in, out := &in.CatalogConnector, &out.CatalogConnector
		*out = new(CatalogConnector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateCatalogConnectorResponse.
func (in *UpdateCatalogConnectorResponse) DeepCopy() *UpdateCatalogConnectorResponse {
	if in == nil {
		return nil
	}
	out := new(UpdateCatalogConnectorResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateConnectorResponse) DeepCopyInto(out *UpdateConnectorResponse) {
	*out = *in
	if in.AffectedTables != nil {
		in, out := &in.AffectedTables, &out.AffectedTables
		*out = make([]TableReference, len(*in))
		copy(*out, *in)
	}
	if in.Connector != nil {
		in, out := &in.Connector, &out.Connector
		*out = new(Connector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateConnectorResponse.
func (in *UpdateConnectorResponse) DeepCopy() *UpdateConnectorResponse {
	if in == nil {
		return nil
	}
	out := new(UpdateConnectorResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateFormatResponse) DeepCopyInto(out *UpdateFormatResponse) {
	*out = *in
	if in.AffectedTables != nil {
		in, out := &in.AffectedTables, &out.AffectedTables
		*out = make([]TableReference, len(*in))
		copy(*out, *in)
	}
	if in.Format != nil {
		in, out := &in.Format, &out.Format
		*out = new(Format)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateFormatResponse.
func (in *UpdateFormatResponse) DeepCopy() *UpdateFormatResponse {
	if in == nil {
		return nil
	}
	out := new(UpdateFormatResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateNamespaceResponse) DeepCopyInto(out *UpdateNamespaceResponse) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(Namespace)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateNamespaceResponse.
func (in *UpdateNamespaceResponse) DeepCopy() *UpdateNamespaceResponse {
	if in == nil {
		return nil
	}
	out := new(UpdateNamespaceResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateSqlScriptResponse) DeepCopyInto(out *UpdateSqlScriptResponse) {
	*out = *in
	if in.SqlScript != nil {
		in, out := &in.SqlScript, &out.SqlScript
		*out = new(SqlScript)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateSqlScriptResponse.
func (in *UpdateSqlScriptResponse) DeepCopy() *UpdateSqlScriptResponse {
	if in == nil {
		return nil
	}
	out := new(UpdateSqlScriptResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateUdfArtifactResponse) DeepCopyInto(out *UpdateUdfArtifactResponse) {
	*out = *in
	if in.CollidingClasses != nil {
		in, out := &in.CollidingClasses, &out.CollidingClasses
		*out = make([]UdfClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MissingClasses != nil {
		in, out := &in.MissingClasses, &out.MissingClasses
		*out = make([]UdfClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UdfArtifact != nil {
		in, out := &in.UdfArtifact, &out.UdfArtifact
		*out = new(UdfArtifact)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateUdfArtifactResponse.
func (in *UpdateUdfArtifactResponse) DeepCopy() *UpdateUdfArtifactResponse {
	if in == nil {
		return nil
	}
	out := new(UpdateUdfArtifactResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidateConfigChangeResponse) DeepCopyInto(out *ValidateConfigChangeResponse) {
	*out = *in
	if in.UnsupportedConfigOptions != nil {
		in, out := &in.UnsupportedConfigOptions, &out.UnsupportedConfigOptions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidateConfigChangeResponse.
func (in *ValidateConfigChangeResponse) DeepCopy() *ValidateConfigChangeResponse {
	if in == nil {
		return nil
	}
	out := new(ValidateConfigChangeResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidateStatementResponse) DeepCopyInto(out *ValidateStatementResponse) {
	*out = *in
	if in.ErrorDetails != nil {
		in, out := &in.ErrorDetails, &out.ErrorDetails
		*out = new(ErrorDetails)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidateStatementResponse.
func (in *ValidateStatementResponse) DeepCopy() *ValidateStatementResponse {
	if in == nil {
		return nil
	}
	out := new(ValidateStatementResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VvpColumn) DeepCopyInto(out *VvpColumn) {
	*out = *in
	if in.Meta != nil {
		in, out := &in.Meta, &out.Meta
		*out = new(VvpColumnMeta)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VvpColumn.
func (in *VvpColumn) DeepCopy() *VvpColumn {
	if in == nil {
		return nil
	}
	out := new(VvpColumn)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VvpColumnMeta) DeepCopyInto(out *VvpColumnMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VvpColumnMeta.
func (in *VvpColumnMeta) DeepCopy() *VvpColumnMeta {
	if in == nil {
		return nil
	}
	out := new(VvpColumnMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VvpSchema) DeepCopyInto(out *VvpSchema) {
	*out = *in
	if in.Column != nil {
		in, out := &in.Column, &out.Column
		*out = make([]VvpColumn, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PrimaryKey != nil {
		in, out := &in.PrimaryKey, &out.PrimaryKey
		*out = new(VvpUniqueConstraint)
		(*in).DeepCopyInto(*out)
	}
	if in.WatermarkSpec != nil {
		in, out := &in.WatermarkSpec, &out.WatermarkSpec
		*out = make([]VvpWatermark, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VvpSchema.
func (in *VvpSchema) DeepCopy() *VvpSchema {
	if in == nil {
		return nil
	}
	out := new(VvpSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VvpTable) DeepCopyInto(out *VvpTable) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Schema != nil {
		in, out := &in.Schema, &out.Schema
		*out = new(VvpSchema)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VvpTable.
func (in *VvpTable) DeepCopy() *VvpTable {
	if in == nil {
		return nil
	}
	out := new(VvpTable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VvpUniqueConstraint) DeepCopyInto(out *VvpUniqueConstraint) {
	*out = *in
	if in.Column != nil {
		in, out := &in.Column, &out.Column
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VvpUniqueConstraint.
func (in *VvpUniqueConstraint) DeepCopy() *VvpUniqueConstraint {
	if in == nil {
		return nil
	}
	out := new(VvpUniqueConstraint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VvpView) DeepCopyInto(out *VvpView) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Schema != nil {
		in, out := &in.Schema, &out.Schema
		*out = new(VvpSchema)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VvpView.
func (in *VvpView) DeepCopy() *VvpView {
	if in == nil {
		return nil
	}
	out := new(VvpView)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VvpWatermark) DeepCopyInto(out *VvpWatermark) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VvpWatermark.
func (in *VvpWatermark) DeepCopy() *VvpWatermark {
	if in == nil {
		return nil
	}
	out := new(VvpWatermark)
	in.DeepCopyInto(out)
	return out
}
